# Generated by Django 5.1.4 on 2025-01-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_profile_picture_categories_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='user',
        ),
    ]
