# Generated by Django 5.1.4 on 2025-01-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_categories_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='user',
        ),
    ]
