# Generated by Django 5.1.4 on 2025-01-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_meals_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
