# Generated by Django 5.1.4 on 2025-01-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_meals_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
